import type { Guideline, LawReference, Project, RoleCode } from "./types";

export const PROJECT_NAME = "G-MADE 체크리스트 사전검토 시스템";

export const roles: Array<{ code: RoleCode; label: string; authority: string }> = [
  { code: "ADMIN", label: "관리자", authority: "평가항목, 기준, 가중치, 사용자, 통계 관리" },
  { code: "REVIEWER", label: "심사위원", authority: "프로젝트 열람, 평가 수행, 의견 작성, AI 결과 확인" },
  { code: "OFFICER", label: "공무원", authority: "사업 등록, 자료 업로드, 결과 확인, 보고서 출력" },
];

export const projects: Project[] = [
  {
    id: "project-001",
    name: "동부역세권 복합문화시설 경관사전심의",
    location: "서울특별시 성동구 왕십리로 222",
    locationPoint: { x: 127.037, y: 37.5613, source: "address" },
    client: "서울도시개발공사",
    designer: "GMA 도시건축사사무소",
    projectType: "복합문화시설",
    scale: "지하 4층 / 지상 18층, 연면적 42,600㎡",
    reviewType: "경관사전심의",
    receivedAt: "2026-06-04",
    status: "접수",
    files: [],
  },
  {
    id: "project-002",
    name: "서부 수변공원 공공디자인심의",
    location: "서울특별시 마포구 망원한강로 14",
    locationPoint: { x: 126.8965, y: 37.5551, source: "address" },
    client: "마포구청",
    designer: "도시공간연구소",
    projectType: "공공공간",
    scale: "공원 18,200㎡, 보행교 1식",
    reviewType: "공공디자인심의",
    receivedAt: "2026-05-29",
    status: "접수",
    files: [],
  },
  {
    id: "project-003",
    name: "남부 생활SOC 복합센터 경관심의",
    location: "경기도 성남시 수정구 수정로 210",
    locationPoint: { x: 127.1598, y: 37.4513, source: "address" },
    client: "성남시",
    designer: "공공건축기획단",
    projectType: "생활SOC",
    scale: "지상 6층, 연면적 9,800㎡",
    reviewType: "경관심의",
    receivedAt: "2026-05-21",
    status: "접수",
    files: [],
  },
  {
    id: "project-004",
    name: "북부 산업단지 진입관문 경관개선 심의",
    location: "경기도 고양시 일산동구 고봉로 32",
    locationPoint: { x: 126.7707, y: 37.6889, source: "address" },
    client: "고양도시관리공사",
    designer: "어반링크 디자인랩",
    projectType: "기반시설",
    scale: "진입도로 1.8km, 상징게이트 2개소",
    reviewType: "경관심의",
    receivedAt: "2026-05-18",
    status: "접수",
    files: [],
  },
  {
    id: "project-005",
    name: "중앙로 보행친화 가로환경 공공디자인심의",
    location: "대전광역시 중구 중앙로 101",
    locationPoint: { x: 127.4215, y: 36.3279, source: "address" },
    client: "대전광역시",
    designer: "공공디자인 스튜디오 봄",
    projectType: "공공공간",
    scale: "가로환경 980m, 쉼터 6개소",
    reviewType: "공공디자인심의",
    receivedAt: "2026-05-14",
    status: "접수",
    files: [],
  },
  {
    id: "project-006",
    name: "해안 문화복합시설 야간경관 사전검토",
    location: "부산광역시 해운대구 해운대해변로 264",
    locationPoint: { x: 129.1604, y: 35.1587, source: "address" },
    client: "부산관광공사",
    designer: "라이트스케이프 건축",
    projectType: "문화시설",
    scale: "지하 2층 / 지상 9층, 연면적 18,400㎡",
    reviewType: "경관사전심의",
    receivedAt: "2026-05-09",
    status: "접수",
    files: [],
  },
  {
    id: "project-007",
    name: "혁신도시 공공청사 증축 경관심의",
    location: "전북특별자치도 전주시 덕진구 시청로 10",
    locationPoint: { x: 127.148, y: 35.8242, source: "address" },
    client: "전북특별자치도",
    designer: "한빛 공공건축사사무소",
    projectType: "공공청사",
    scale: "지상 8층, 연면적 15,200㎡",
    reviewType: "경관심의",
    receivedAt: "2026-05-02",
    status: "접수",
    files: [],
  },
  {
    id: "project-008",
    name: "동남권 복합환승센터 경관사전심의",
    location: "서울특별시 송파구 마천로 111",
    locationPoint: { x: 127.1267, y: 37.4784, source: "address" },
    client: "서울교통공사",
    designer: "메트로폴리스 플랜",
    projectType: "교통시설",
    scale: "환승센터 1식, 광장 12,500㎡",
    reviewType: "경관사전심의",
    receivedAt: "2026-04-26",
    status: "접수",
    files: [],
  },
];

export const laws: LawReference[] = [
  { id: "law-landscape", title: "경관법", article: "제28조", summary: "경관심의 대상과 기준에 관한 사항", jurisdiction: "국토교통부" },
  { id: "law-ordinance", title: "서울특별시 경관 조례", article: "제18조", summary: "색채 및 건축경관 심의 기준", jurisdiction: "서울특별시" },
  { id: "law-light", title: "인공조명에 의한 빛공해 방지법", article: "제11조", summary: "조명환경관리구역과 빛방사 허용 기준", jurisdiction: "환경부" },
  { id: "law-universal", title: "장애인등편의법", article: "제8조", summary: "접근로와 편의시설 설치 기준", jurisdiction: "보건복지부" },
  { id: "law-green", title: "도시공원 및 녹지 등에 관한 법률", article: "제35조", summary: "녹지 확보와 도시 생태성 기준", jurisdiction: "국토교통부" },
  { id: "law-public-design", title: "공공디자인의 진흥에 관한 법률", article: "제10조", summary: "공공디자인 심의와 품질관리", jurisdiction: "문화체육관광부" },
  { id: "law-admin", title: "행정절차법", article: "제17조", summary: "신청 서류의 접수와 보완 절차", jurisdiction: "행정안전부" },
];

export const guidelines: Guideline[] = [
  { id: "guide-skyline", title: "도시 스카이라인 관리지침", section: "3.2", summary: "주요 조망축과 높이 변화 관리" },
  { id: "guide-facade", title: "건축물 입면 경관 가이드라인", section: "2.1", summary: "저층부 개방감과 입면 분절" },
  { id: "guide-color", title: "서울색 적용 가이드", section: "4.4", summary: "권역별 주조색과 강조색 운용" },
  { id: "guide-night", title: "야간경관 조명 가이드라인", section: "5.3", summary: "휘도, 색온도, 빛공해 저감" },
  { id: "guide-walk", title: "보행친화도시 설계지침", section: "2.5", summary: "연속 보행축과 교통약자 접근성" },
  { id: "guide-green", title: "도시녹지 네트워크 계획기준", section: "3.1", summary: "가로녹지와 공개공지 식재 연결" },
  { id: "guide-public-space", title: "공공공간 디자인 매뉴얼", section: "6.2", summary: "체류형 공개공지와 시설물 배치" },
  { id: "guide-document", title: "경관심의 제출도서 체크리스트", section: "1.1", summary: "필수 도면과 시각자료 제출 기준" },
];
